<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\JabatanAparatDesa;
use App\Enums\JenisSuratPengantar;
use App\Models\AparatDesa;
use App\Models\Desa;
use App\Models\Kelahiran;
use App\Models\Penduduk;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\SuratPengantar>
 */
class SuratPengantarFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $jenisSurat = fake()->randomElement(JenisSuratPengantar::cases());

        return [
            'desa_id' => Desa::factory(),
            'penduduk_id' => Penduduk::factory(),
            'kelahiran_id' => null, // Will be set for KELAHIRAN type
            'jenis_surat' => $jenisSurat,
            'nama_pemohon' => fake()->name(),
            'nik_pemohon' => fake()->numerify('################'),
            'ditujukan_kepada' => $jenisSurat->getTujuanDefault() ?? fake()->company(),
            'keperluan' => fake()->optional(0.7)->sentence(),

            // Data Spesifik (JSON) - akan diisi sesuai jenis
            'data_skck' => null,
            'data_nikah' => null,
            'data_pindah' => null,
            'data_dokumen' => null,
            'data_kelahiran' => null,
            'data_tambahan' => null,

            // Data Pelapor (JSON) - opsional
            'data_pelapor' => null,

            // Tanda Tangan Pemohon
            'ttd_pemohon' => null,
            'foto_ttd_pemohon' => null,

            // Dokumen Pendukung (JSON)
            'dokumen_pendukung' => null,

            // Surat
            'no_surat' => null, // Auto-generated by Observer
            'tanggal_surat' => fake()->dateTimeBetween('-6 months', 'now'),
            'kepala_desa_id' => null, // Will be set in seeder
            'keterangan' => fake()->optional(0.3)->sentence(),
        ];
    }

    /**
     * State untuk jenis SKCK
     */
    public function skck(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratPengantar::SKCK,
            'ditujukan_kepada' => 'Kepolisian Sektor (Polsek) ' . fake()->city(),
            'data_skck' => [
                'keperluan' => fake()->randomElement(['Melamar Pekerjaan', 'Administrasi', 'Pencalonan']),
                'pekerjaan' => fake()->jobTitle(),
            ],
        ]);
    }

    /**
     * State untuk jenis NIKAH
     */
    public function nikah(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratPengantar::NIKAH,
            'ditujukan_kepada' => 'Kantor Urusan Agama (KUA) ' . fake()->city(),
            'data_nikah' => [
                'nama_calon_pasangan' => fake()->name(),
                'tanggal_rencana_nikah' => fake()->dateTimeBetween('now', '+6 months')->format('Y-m-d'),
            ],
        ]);
    }

    /**
     * State untuk jenis KELAHIRAN
     */
    public function kelahiran(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratPengantar::KELAHIRAN,
            'kelahiran_id' => Kelahiran::factory(),
            'ditujukan_kepada' => 'Dinas Kependudukan dan Catatan Sipil',
            'data_kelahiran' => [
                'nama_bayi' => fake()->name(),
                'tanggal_lahir' => fake()->dateTimeBetween('-1 year', 'now')->format('Y-m-d'),
                'tempat_lahir' => fake()->randomElement(['Rumah Sakit', 'Puskesmas', 'Rumah']),
            ],
        ]);
    }

    /**
     * State untuk jenis PINDAH
     */
    public function pindah(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratPengantar::PINDAH,
            'ditujukan_kepada' => 'Dinas Kependudukan dan Catatan Sipil',
            'data_pindah' => [
                'alamat_tujuan' => fake()->address(),
                'alasan_pindah' => fake()->randomElement(['Pekerjaan', 'Pendidikan', 'Ikut Keluarga']),
            ],
        ]);
    }
}
