<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\JabatanAparatDesa;
use App\Enums\JenisSuratKeterangan;
use App\Models\AparatDesa;
use App\Models\Desa;
use App\Models\Kematian;
use App\Models\Penduduk;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\SuratKeterangan>
 */
class SuratKeteranganFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $jenisSurat = fake()->randomElement(JenisSuratKeterangan::cases());

        return [
            'desa_id' => Desa::factory(),
            'penduduk_id' => Penduduk::factory(),
            'kematian_id' => null, // Will be set for KEMATIAN type
            'jenis_surat' => $jenisSurat,
            'keperluan' => fake()->optional(0.7)->sentence(),
            'nama_pemohon' => fake()->name(),
            'nik_pemohon' => fake()->numerify('################'),

            // Data Spesifik (JSON) - akan diisi sesuai jenis
            'data_domisili' => null,
            'data_usaha' => null,
            'data_ekonomi' => null,
            'data_pernikahan' => null,
            'data_ahli_waris' => null,
            'data_kematian' => null,
            'data_tambahan' => null,

            // Data Pelapor (JSON) - opsional
            'data_pelapor' => null,

            // Tanda Tangan Pemohon
            'ttd_pemohon' => null,
            'foto_ttd_pemohon' => null,

            // Dokumen Pendukung (JSON)
            'dokumen_pendukung' => null,

            // Surat
            'no_surat' => null, // Auto-generated by Observer
            'tanggal_surat' => fake()->dateTimeBetween('-6 months', 'now'),
            'kepala_desa_id' => null, // Will be set in seeder
            'keterangan' => fake()->optional(0.3)->sentence(),
        ];
    }

    /**
     * State untuk jenis DOMISILI
     */
    public function domisili(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratKeterangan::DOMISILI,
            'data_domisili' => [
                'alamat_lengkap' => fake()->address(),
                'rt' => fake()->numerify('0##'),
                'rw' => fake()->numerify('0##'),
                'kelurahan' => fake()->citySuffix(),
                'kecamatan' => fake()->city(),
                'lama_tinggal' => fake()->numberBetween(1, 20) . ' tahun',
            ],
        ]);
    }

    /**
     * State untuk jenis KEMATIAN
     */
    public function kematian(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratKeterangan::KEMATIAN,
            'kematian_id' => Kematian::factory(),
            'data_kematian' => [
                'tanggal_meninggal' => fake()->dateTimeBetween('-1 year', 'now')->format('Y-m-d'),
                'tempat_meninggal' => fake()->randomElement(['Rumah', 'Rumah Sakit', 'Puskesmas']),
                'sebab_kematian' => fake()->randomElement(['Sakit', 'Usia Lanjut', 'Kecelakaan']),
            ],
        ]);
    }

    /**
     * State untuk jenis USAHA
     */
    public function usaha(): static
    {
        return $this->state(fn (array $attributes) => [
            'jenis_surat' => JenisSuratKeterangan::USAHA,
            'data_usaha' => [
                'nama_usaha' => fake()->company(),
                'jenis_usaha' => fake()->randomElement(['Warung', 'Toko', 'Bengkel', 'Penjahit']),
                'alamat_usaha' => fake()->address(),
                'lama_usaha' => fake()->numberBetween(1, 10) . ' tahun',
            ],
        ]);
    }
}
